= SD Light library for Arduino =

This is a rewrite by https://github.com/rizsi of the original Arduino library to only have the essential functions to read/write SD cards and use less SRAM. (Uses almost 0 SRAM bytes.)

Most of the functions are removed this version only reads/writes blocks of the SD card.

See https://github.com/arduino-libraries/SD for the original version.

Original README:

= SD Library for Arduino =

The SD library allows for reading from and writing to SD cards.

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/SD

== License ==

 Copyright (C) 2009 by William Greiman
Copyright (c) 2010 SparkFun Electronics

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
